TheAlgorithms/JavaScript

Sorts/mergeSort.js
Adds the merge sort algorithm, let me know if any code style changes need to be made.
=> #14 - Adding merge sort algorithm

Sorts/cocktailShakerSort.js
Added cocktail shaker sort algorithm
=> Implemented cocktail shaker sort algorithm

Ciphers/caesarsCipher.js
Let me know if any changes are needed!
=> Adding the Caesar's Cipher algorithm

Sorts/bubblesort.js
name of commit :  add console printing for after sorting - 28343d2
=> add last console printing to show after sorting

Sorts/radixSort.js
Added the implementation of the radix sort algorithm.
=> Added radixsort algorithm.

Data Structures/Queue/Queue.js
I tried to follow the style of the Stack implementation closely to reduce confusion. Tested and works well enough. Submitted as part of #14!
=> Added Queue Data Structure

Algorithms/dynamic_programming/fibonacci.js
Simple bottom up implementation of dynamic programming Fibonacci calculation
=> Added bottom up DP implementation of Fibonacci

Sorts/countingSort.js, Sorts/flashSort.js
=> feat: add counting and flash sorts

Sorts/bucketSort.js
=> Implemented bucket sort algorithm

Algorithms/EucledianGCD.js, Algorithms/sieveOfEratosthenes.js, Ciphers/caesarsCipher.js, Conversions/DecimalToBinary.js, Search/binarySearch.js, Search/linearSearch.js, Sorts/bogoSort.js, Sorts/wiggleSort.js, maths/abs.js, maths/average_mean.js, maths/factorial.js, maths/find_lcm.js
I modified the whitespace in the files and changed single quotes to double quotes.
I also changed some `==` and `!=` operators to `===` and `!==` to comply with JSLint.
I added some algorithms to the new 'maths' folder. (Sorry, I did not mean to include the maths algorithms in the smae PR).
=> Improved JSLint Compliance and Created Math Algorithms

maths/factorial.js
=> factorial.js: Standardjs fixes

.github/workflows/update_directory_md.yml, DIRECTORY.md
=> run: node .github/workflows/UpdateDirectory.js 

Cache/LRUCache.js
=> Added LRU Cache

Graphs/ConnectedComponents.js, Graphs/PrimMST.js
=> Small Tweaks/Fixes

DIRECTORY.md, TimingFunctions/IntervalTimer.js
=> Adding TimingFunctions/IntervalTimer

Conversions/BinaryToDecimal.js
* Implemented binary to decimal
=> Implement binary to decimal

Dynamic-Programming/EditDistance.js
=> Added Edit Distance Algorithm in Dynamic-Programming

Maths/Polynomial.js
=> feat: added Polynomial in Maths

String/CheckAnagram.js, String/CheckAnagram.test.js, String/CheckPalindrome.js, String/CheckPalindrome.test.js, String/PatternMatching.js, String/PatternMatching.test.js, String/ReverseString.js, String/ReverseString.test.js, String/ReverseWords.js, String/ReverseWords.test.js, babel.config.js, package-lock.json, package.json
It seems that the test inside Linear-Algebra is failling due to import problems. Instead of opening and reading the file, exporting the LinearAlgebra function may be a better alternative.
* [X ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
=> Added tests for Strings algorithms

Sorts/SelectionSort.js, Sorts/SelectionSort.test.js
=> Fix selection sort and add tests; fixes #414

Sorts/BubbleSort.js
- Added Wikipedia Link.
- Improved Comments and Formatting.
- The first BubbleSort (using 2 for loops) was not returning the array. Changed that.
- Improved the Implementation Examples and Console logs.
- And Finally, added doctests as mentioned in ([Issue #142](https://github.com/TheAlgorithms/Javascript/issues/142))
=> Improved BubbleSort and added Doctests

Data-Structures/Linked-List/RotateListRight.js
=> Added Rotate List Right by k places to the list

Recursive/Palindrome.js
=> palindrome-recursive-algorithm-added

Conversions/HexToRGB.js
Substring indexes were all off by 1, creating an incorrect output.
Also removed unnecessary `toUpperCase()` calls.
=> Fixing incorrect substring indexes

DIRECTORY.md, Sorts/BeadSort.js
Issue #14: adds Bead Sort (aka Gravity Sort) algorithm to Sorts folder according to CONTRIBUTING.md.
Includes doctest mentioned in #142.
=> Add Bead Sort (aka Gravity Sort) Algorithm

Trees/BreadthFirstTreeTraversal.js
=> Implement BreadthFirstTreeTraversal in JavaScript

Timing-Functions/GetMonthDays.js, Timing-Functions/GetMonthDays.test.js
Adding a function that get the number of days of a month, given its number and its year.
=> Add Get Numbers of Days of a Month

Recursive/factorial.js, Recursive/factorialCalculator.js
=> Added tests & normal function convertion

String/CreatePurmutations.js, String/createPurmutations.js
Add a permuation function to get all string permutations
=> Added createPermutation function

Project-Euler/Problem2.js
Update Euler Problem 2 to ES6 standards.
Relates to: #14
=> Update Euler Problem 2 to ES6 standards

Dynamic-Programming/LongestValidParentheses.js
=> Added Longest Valid Parentheses Algorithm

Maths/BinaryExponentiationIterative.js, Maths/test/BinaryExponentiationIterative.test.js
=> Add Iterative Binary Exponentiation

String/ValidateEmail.js, String/test/ValidateEmail.test.js
=> Modify ValidateEmail.js to accept all suffixes not just '.com'

CONTRIBUTING.md
I have added [Doctest](https://www.npmjs.com/package/doctest) contribution guidelines to [Contributing.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x ] This pull request is all my own work -- I have not plagiarized.
=> Doctest contribution Guidelines added to Contributing.md

Maths/decimalIsolate.js, Maths/isOdd.js
* [X ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [X ] I know that pull requests will not be merged if they fail the automated tests.
* [X ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X ] All new JavaScript files are placed inside an existing directory.
* [ X] All new algorithms have a URL in its comments that points to Wikipedia or …
=> Added decimalIsolate function.

DIRECTORY.md, Search/QuickSelectSearch.js
#14 I've added Quick Select algorithm
=> Added QuickSelect  Algorithm

Data-Structures/Tree/AVLTree.js
=> AVL Tree Added in JS Fixes:#535

String/ReverseString.js
=> #142 #461 Adding Doctests to String/ReverseString.js

String/ValidateEmail.js
=> #142 #461 Adding Doctests to String/ValidateEmail.js

Maths/Factorial.js, Maths/test/Factorial.test.js
=> Refactor Maths/Factorial for more minimal side effects.

Maths/EulerMethod.js
=> Add algorithm Euler method

Conversions/RgbHsvConversion.js
=> Add RGB-HSV conversion

.github/workflows/nodejs.yml, Conversions/DecimalToBinary.js, Conversions/HexToRGB.js, Conversions/RomanToDecimal.js, Data-Structures/Linked-List/SinglyLinkList.js, Data-Structures/Stack/Stack.js, Data-Structures/Tree/BinarySearchTree.js, Data-Structures/Tree/Trie.js, Dynamic-Programming/ZeroOneKnapsack.js, Linear-Algebra/src/la_lib.js, Linear-Algebra/test/test.js, Maths/Fibonacci.js, Maths/Polynomial.js, Search/LinearSearch.js, Sorts/GnomeSort.js, Sorts/HeapSort.js, Sorts/InsertionSort.js, Sorts/IntroSort.js, Sorts/MergeSort.js, Sorts/QuickSort.js, Sorts/RadixSort.js, Sorts/SelectionSort.test.js, Sorts/ShellSort.js, Sorts/TopologicalSort.js, Sorts/WiggleSort.js, String/LevenshteinDistance.test.js, String/PermutateString.js, Trees/DepthFirstSearch.js, package-lock.json
=> Fix entire codebase

Sorts/SleepSort.js
Added the algorithm for Sleep Sort.
=> Added Sleep Sort

Backtracking/NQueen.js, Backtracking/tests/NQueen.test.js
- Find all solutions for NQueen problem
- Add unittest for NQueen.js
- Refactor some codes
Fixes #620
=> Find all the solutions of NQueen

Data-Structures/Array/QuickSelect.js
Releated issue #142 
- Add doctest on quickselect algorithm
=> Add doctest on quickselect algorithm

Project-Euler/Problem015.js
=> Add solution for Project-Euler Problem15

Search/TernarySearch.js, Search/test/TernarySearch.test.js
=> Added TernarySearch Function

Graphs/BellmanFord.js, Graphs/test/BellmanFord.test.js
=> Added BellmanFord

Maths/SumOfDigits.js, Maths/test/SumOfDigits.test.js, package-lock.json
The related question: https://the-algorithms.com/algorithm/sum-of-digits
There's no JavaScript implementation, so I implemented in JS. Also, I might have messed up writing the tests, since it was not exactly clear to me. So I'd request to please crosscheck the tests(, and if I have any mistake/error in there, I'll fix it)
=> Added Sum of Digits Implementation

Data-Structures/Array/QuickSelect.js, Data-Structures/Array/QuickSelect.test.js
=> Quick select tests

Backtracking/SumOfSubset.js, Backtracking/tests/SumOfSubset.test.js
=> Added backtracking sum of subset

String/CheckCamelCase.js, String/test/CheckCamelCase.test.js
The goal of this PR is to add tests for the CheckCamelCase algorithm. It also changes CheckCamelCase.js in order to respect Javascript  ES6 standard
=> Add test for camel case algorithm

String/MaxWord.js, String/test/MaxWord.test.js
=> Add max word algorithm

Conversions/TitleCaseConversion.js, Conversions/test/TitleCaseConversion.test.js
=> Title case conversion tests

Backtracking/AllCombinationsOfSizeK.js, Backtracking/tests/AllCombinationsOfSizeK.test.mjs, package-lock.json, package.json
- Added a new algorithm AllCombinationsOfSizeK in Backtracking
=> added Backtracking/AllCombinationsOfSizeK

Dynamic-Programming/KadaneAlgo.js, Dynamic-Programming/tests/KadaneAlgo.test.js
Added documentation, js standard style and jest testing to kadane algorithm file.
=> added documentation, js standard style and jest testing to kadane algorithm file.

DIRECTORY.md, Maths/BisectionMethod.js, Maths/test/BisectionMethod.test.js
Added bisection method for root approximation in  a given interval
Unit tests included (Jest)
Formatted with standard.js
=> Added bisection method 

DIRECTORY.md, String/ValidateCreditCard.js, String/test/ValidateCreditCard.test.js
Add credit card number string validator
=> Strings: Credit Card Validation

Dynamic-Programming/ClimbingStairs.js, Dynamic-Programming/tests/ClimbingStairs.test.js
=> add test case and description

Navigation/Haversine.js
=> add description

Data-Structures/Queue/Queue.js, Data-Structures/Queue/test/Queue.test.js
=> Refactor Code and Add test case

Sorts/QuickSort.js
=> Add Description and Optamization

Recursive/Palindrome.js, Recursive/test/palindrome.test.js
=> Add test Case for Palindrome Recursive

Data-Structures/Linked-List/SinglyLinkList.js, Data-Structures/Linked-List/test/SinglyLinkList.test.js
=> Add test case and enacements

Maths/Abs.js, Maths/test/Abs.test.js
=> Absolute value

Maths/BinaryConvert.js, Maths/test/BInaryConvert.test.js
=> Binary Convert

Maths/AverageMean.js, Maths/test/AverageMean.test.js
=> Improve Mean method

Trees/BreadthFirstTreeTraversal.js
Breadth First Tree Traversal:
* Let traverseLevel return early if node is null
* Replace `node == null` with `node === null`
=> Breadth First Tree Traversal: Let traverseLevel return early if node is null

Recursive/BinarySearch.js, Recursive/test/BinarySearch.test.js, package.json
* Parameters added according to the convention
* Early return base case added
#883
=> binarySearch

Maths/AverageMean.js
The URL in the Wikipedia link (of AverageMean.js) had an extra "h" in the URI Scheme (the part that specifies the protocol, usually `https`). I removed the duplicate "h" and made it into a single "h", now the link works. I have not plagiarized (because I'm not claiming work as mine), but the pull request contains work (the algorithm) from someone else, so I left the box unchecked because I didn't know what to do.
=> Corrected JSdoc typo

Maths/ArithmeticGeometricMean.js, Maths/test/ArithmeticGeometricMean.test.js
Added an algorithm to compute/find the Arithmetic-Geometric Mean between 2 numbers `a` and `g`. I thought it would be a good idea since it shows how to compute at full precision without an `epsilon` comparison, and there's already an Arithmetic Mean so I added this for completeness.
=> Algorithm to calculate the Arithmetic Geometric Mean

String/CheckAnagram.js, String/test/CheckAnagram.test.js
=> Upgrade `checkAnagram` function & Fixes

Sorts/InsertionSort.js, Sorts/test/InsertionSort.test.js
=> Add alternative implementation for `InsertionSort` and relative test.

.husky/pre-commit, package-lock.json, package.json
=> Run "style" and "test" scripts automatically when committing new changes

Maths/IsEven.js, Maths/test/IsEven.test.js
=> refactor `isEven` function

Maths/Abs.js, Maths/test/Abs.test.js
=> Improved `abs` function

Conversions/test/DecimalToBinary.test.js, Conversions/test/DecimalToOctal.test.js, Conversions/test/OctToDecimal.test.js
- [✅  ] I know that pull requests will not be merged if they fail the automated tests.
- [ ✅ ] All new JavaScript files are placed inside an existing directory. …
=> Add test case to DecimalToBinary,DecimalToOctal & OctToDecimal

Cache/Memoize.js, Cache/test/Memoize.test.js
=> Added explicit cache feature & optional parameter

Data-Structures/Graph/Graph3.js, Data-Structures/Graph/test/Graph3.test.js
- [o] New Implementation of Data Structure
- [o] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [o] This pull request is all my own work -- I have not plagiarized.
- [o] I know that pull requests will not be merged if they fail the automated tests.
- [o] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [o] All new JavaScript files are placed inside an existing directory.
- [o] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
**Example:**`UserProfile.js` is …
=> Add Graph3 (add DFS in Iterative Way)

Cache/LRUCache.js, Cache/test/LRUCache.test.js
=> Improved `LRUCache`

Ciphers/Atbash.js, Ciphers/test/Atbash.test.js
=> Improved ciphers

String/Lower.js, String/Upper.js, String/test/Lower.test.js, String/test/Upper.test.js
=> reduce upper & lower & add export default

Maths/FindLcm.js
=> FindLCM: Improve code readablility

Maths/WhileLoopFactorial.js, Maths/test/WhileLoopFactorial.test.js
=> WhileLoopFactorial: Optimize and add tests

Maths/ZellersCongruenceAlgorithm.js, Maths/test/ZellersCongruenceAlgorithm.test.js
=> Add Zeller's Congruence Algorithm in Math

Sorts/SimplifiedWiggleSort.js, Sorts/WiggleSort.js, Sorts/test/SimplifiedWiggleSort.test.js
Fixes: #988
Renamed the algorithm "simplified wiggle-sort", because traditional wiggle-sort demands arr[0] < arr[1] > arr[2] < arr[3] > arr[4] <... but this version only demands arr[0] <= arr[1] >= arr[2] <= arr[3] >= arr[4] <= …
For strict wiggle-sort there could be made an own implementation.
- [] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
=> Fix wiggle sort

README.md
The current `README.md` is a bit all over the place, which is bad since it is the main document that visitors to the repository sees. This pull request seeks to fix that.
=> A better `README`

Maths/IsDivisible.js
This PR edits the error message in that file (Maths/IsDivisible.js) to be more accurate to its context. Because `Infinity` and `NaN` aren't valid Real numbers.
=> More accurate error message at `IsDivisible`

Maths/Fibonacci.js, Maths/test/Fibonacci.test.js
Added `BigInt` support to `FibonacciMatrixExpo`, `Identity`, `matrixMultiply`, and `matrixExpo`. And added the extension to negative domain for all fns in that file. And added a *generator* function example. Also corrected indices to return 0 if the input arg is 0 (because that's the 0th Fib).
Fixes: #1047
=> `Fibonacci.js` overhaul

DIRECTORY.md, Maths/GetEuclidGCD.js
Implement the actual Euclidean Algorithm
=> Fix GetEuclidGCD

DIRECTORY.md, Maths/GetEuclidGCD.js, Maths/ShorsAlgorithm.js, Maths/test/ShorsAlgorithm.test.js
Implemented the classical version of Shor's quantum algorithm for factorizing integers.
=> Implement Shor's factorization algorithm

Data-Structures/Tree/AVLTree.js, Data-Structures/Tree/test/AVLTree.test.js
The original insertBalance function was doing raw value comparisons as opposed to using the tree's comparator. This is clearly unintentional, and would (ultimately) cause the structure to segfault when constructed with the stringData included in the updated test.
I've added the fix, scanned the rest of the code for similar issues, and added the appropriate test case which passes successfully with the fix. The jest code coverage increases slightly as well with the changes. Have also run the updated code against Standard JS linter and looks good. …
=> Bugfix AVLTree comparator

Maths/Factorial.js, Maths/test/Factorial.test.js
=> fix: factorial function

Data-Structures/Tree/AVLTree.js, Data-Structures/Tree/test/AVLTree.test.js
Jest output prior to changes:
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
------------|---------|----------|---------|---------|---------------------------------
All files   |   89.43 |    85.48 |     100 |   90.51 |
AVLTree.js |   89.43 |    85.48 |     100 |   90.51 | ...,122-123,154-155,157-158,162
Jest output after changes:
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
------------|---------|----------|---------|---------|-------------------
All files   |     100 |      100 |     100 |     100 |
AVLTree.js |     100 |      100 |     100 |     100 | …
=> feat: AVLTree 100% test coverage

Data-Structures/Linked-List/CycleDetection.js, Data-Structures/Linked-List/test/CycleDetection.test.js
=> refactor: Cycledetection.js and added tests

CONTRIBUTING.md, Dynamic-Programming/LevenshteinDistance.js, Dynamic-Programming/tests/LevenshteinDistance.test.js
=> tests: Levenshtein Distance (dynamic programming solution)

Search/Minesweeper.js, Search/test/Minesweeper.test.js
- [x ] This pull request is all my own work -- I have not plagiarized.
=> algorithm: Minesweeper

Maths/CircularArc.js, Maths/test/CircularArc.test.js
=> Add an algorithm to find length of an arc and area of the sector formed by an arc of a circle

Project-Euler/Problem007.js, Project-Euler/test/Problem007.test.js
=> solution: ProjectEuler-007

Conversions/DateToDay.js, Conversions/test/DateToDay.test.js
=> fix: DateToDay

Project-Euler/Problem028.js, Project-Euler/test/Problem028.test.js
=> solution: Project Euler Problem 28

Trees/FenwickTree.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1208"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: fix typos

Maths/ModularArithmetic.js, Maths/test/ModularArithmetic.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1217"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added-ModularArithmetic-code

Maths/FindLcm.js
It seems like for some reason, my recent PR broke the builds in the continuous integration, even though it passed locally and in the PR. Not 100% sure why it happened in one place but not the others, but in any event, it seems to be due to a capitalization error which I fix in this PR.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1223"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: build error due to FindLcm

Recursive/Factorial.js, Recursive/test/Factorial.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1229"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: check for invalid input to factorial

Graphs/BinaryLifting.js, Graphs/LCABinaryLifting.js, Graphs/test/LCABinaryLifting.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1237"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: LCA by binary lifting

Data-Structures/Linked-List/ReverseSinglyLinkedList.js, Data-Structures/Linked-List/SinglyLinkedList.js, Data-Structures/Linked-List/test/ReverseSinglyLinkedList.test.js, Data-Structures/Linked-List/test/SinglyLinkedList.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1241"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: add reverse to singly linked list

Conversions/OuncesToKilograms.js, Conversions/test/OuncesToKilogram.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1248"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> convertion: ounce to kilogram

Geometry/Pyramid.js, Geometry/Test/Pyramid.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1254"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm class: pyramid

String/ZFunction.js, String/test/ZFunction.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1239"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: ZFunction

Maths/SquareRootLogarithmic.js, Maths/test/SquareRootLogarithmic.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1259"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: logarithmic square root

Maths/FriendlyNumbers.js
Added a new FriendlyNumbers.js file, with a Maths algorith to determine if two integers are friendly numbers.  Friendaly number are defined as follows (source wikipedia):   'In number theory, friendly numbers are two or more natural numbers with a common abundancy index, the  ratio between the sum of divisors of a number and the number itself.'
This is my first ever real pull request as I am totally new to git and gitHub. Please don't hesitate to let me now if I am not following the proper procedure.
- [x ] Add an algorithm?
**Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.j …
=> Added a new Maths algorithm to determine if two non-null integers are "friendly numbers"

Maths/Signum.js, Maths/test/Signum.test.js
This PR is to add the implementation of the signum function. TheAlgorithms entry is [here](https://the-algorithms.com/algorithm/signum)
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1266"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: signum

CONTRIBUTING.md
**Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not~
=> docs: improve the contributing guidelines

Cache/Memoize.js, Ciphers/test/AffineCipher.test.js, Ciphers/test/KeywordShiftedAlphabet.test.js, Ciphers/test/VigenereCipher.test.js, Conversions/BinaryToHex.js, Conversions/RailwayTimeConversion.js, Conversions/test/TemperatureConversion.test.js, Data-Structures/Array/LocalMaximomPoint.js, Data-Structures/Tree/Trie.js, Dynamic-Programming/KadaneAlgo.js, Dynamic-Programming/UniquePaths2.js, Geometry/Circle.js, Graphs/BinaryLifting.js, Graphs/LCABinaryLifting.js, Maths/BinomialCoefficient.js, Maths/CheckKishnamurthyNumber.js, Maths/ExtendedEuclideanGCD.js, Maths/FermatPrimalityTest.js, Maths/test/MeanAbsoluteDeviation.test.js, Project-Euler/Problem003.js, Project-Euler/Problem008.js, Project-Euler/Problem023.js, Project-Euler/Problem028.js, Sorts/IntroSort.js
- N/A? - This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
This PR fixes some miscellaneous typos. I used it as a trial run for [a CLI I made](https://github.com/Lioness100/rspell) :)
Note: https://github.com/TheAlgorithms/JavaScript/blob/8cd86b1eda32a58f34c3da21b5aa201e8dee3fd5/Ciphers/AffineCipher.js#L11 "modulas" might be a typo? I'm not sure.
=> docs: fix typos

Data-Structures/Linked-List/SinglyLinkedList.js, Data-Structures/Linked-List/test/SinglyLinkedList.test.js
=> Refactored code to improve performance of some methods

Backtracking/generateParentheses.js, Backtracking/tests/GenerateParentheses.test.js
- [ Add ] I Added generate parentheses algorithm(inside backtracking folder)
- [ fix ] I fixed the jtest file (GenerateParentheses.test.js)
- [ fix ] I used a proper JSDoc comments
=> Adding to backtracking

Conversions/ArbitraryBase.js, Conversions/test/ArbitraryBase.test.js
https://mathiasbynens.be/notes/javascript-unicode#counting-symbols
=> Make ArbitraryBase Unicode-aware

Cellular-Automata/Elementary.js, Cellular-Automata/test/Elementary.test.js
Noticed that Conway's Game of Life was lonely in the Cellular Automata folder, so I decided to add the 1D Elementary cellular automata to keep it company.
=> Elementary cellular automata

Data-Structures/Linked-List/SinglyLinkedList.js, Data-Structures/Linked-List/test/SinglyLinkedList.test.js
=> fix error in SinglyLinkedList head method

Project-Euler/Problem021.js, Project-Euler/test/Problem021.test.js
=> Project Euler 021

Backtracking/AllCombinationsOfSizeK.js, Data-Structures/Array/LocalMaximomPoint.js, Data-Structures/Graph/Graph2.js
=> fix a few typos in comments

Bit-Manipulation/IsPowerofFour.js, Bit-Manipulation/test/IsPowerOfFour.test.js
=> added algo for checking the number is power of four or not

Maths/Palindrome.js, Maths/test/Palindrome.test.js
I added an algo for checking the string is palindrome or not.
=> added an algo for checking the string is palindrome or not

Conversions/LengthConversion.js, Conversions/test/LengthConversion.test.js
I have added Algorithms for Length Conversion.
Issue #1391
=> Add Length Conversion

DIRECTORY.md, Project-Euler/test/Problem044.test.js
It's good to have the test there, but there's no use having it running for ~30 minutes or so in the GitHub Action
close #1193
- [x ] Fix a bug or typo in an existing algorithm?
=> test: skip test that's running way too long

Backtracking/GeneratePermutations.js
- Fixes #1452
-Fixes the Grammar Mistake
=> Fixes-the-Grammar-Mistake

Bit-Manipulation/GrayCodes.js, Bit-Manipulation/test/GrayCodes.test.js
- [Yes] Add an algorithm?
- [Yes ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [Yes ] This pull request is all my own work -- I have not plagiarized.
- [Yes ] I know that pull requests will not be merged if they fail the automated tests.
- [Yes ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ Yes] All new JavaScript files are placed inside an existing directory.
- [Yes ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
**Example:**`UserProfile.js` is …
=> feat: added Gray Code algorithm

Data-Structures/Stack/EvaluateExpression.js, Data-Structures/Stack/test/EvaluateExpression.test.js
=> feat: add algorithm to evaluate postfix string

Maths/Determinant.js, Maths/test/Determinant.test.js
=> feat: add determinant algorithm

Data-Structures/Linked-List/MergeTwoSortedLinkedLists.js, Data-Structures/Linked-List/test/MergeTwoSortedLinkedLists.test.js
=> feat: add MergeTwoSortedLinkedLIsts algorithms

Conversions/RgbHslConversion.js, Conversions/test/RgbHslConversion.test.js
=> feat: add RGB to HSL color format conversion algorithm

Hashes/SHA256.js
=> docs: fix typo in existing docstring (SHA256.js)

Backtracking/KnightTour.js
Added comments at various parts of the KnightTour.js file to enhance readability and understandability of the code.
=> Enhance readability of KnightTour

.github/workflows/Ci.yml, Backtracking/MColoringProblem.js, Backtracking/tests/MColoringProblem.test.js, DIRECTORY.md, package.json
This PR makes the CI use `--check` rather than `--write` so that CI fails if code isn't formatted properly.
=> fix: CI code style checking

Hashes/MD5.js, Hashes/tests/MD5.test.js
=> feat: Added MD5 hashing algorithm

Dynamic-Programming/ZeroOneKnapsack.js
Incorporated comments that explain the Memoization (Top Down) approach for solving the 0/1 Knapsack problem. In addition, I've employed the "pick" and "notPick" variables to enhance the code's readability and comprehensibility.
=> Enhance readability of ZeroOneKnapsack.js

Backtracking/tests/KnightTour.test.js
This PR adds a test covering this line: https://github.com/TheAlgorithms/JavaScript/blob/069803f2718b379b8c1b67c5da6e74820bd57cce/Backtracking/KnightTour.js#L41
=> Add missing test for `KnightTour`

Hashes/tests/SHA1.test.js
This PR adds test for [`SHA1`](https://github.com/TheAlgorithms/JavaScript/blob/cf0004190ab69c947d781f5cb8537b446beb8cbf/Hashes/SHA1.js). The test data comes from [wikipeda](https://en.wikipedia.org/wiki/SHA-1) or was verified with http://www.sha1-online.com/
=> tests: add tests for `SHA1`

Hashes/tests/SHA256.test.js
This PR adds tests for [`SHA256`](https://github.com/TheAlgorithms/JavaScript/blob/6aaa376500a7312d6980957c5ac2288282d0bed7/Hashes/SHA256.js).
The data was verified with https://emn178.github.io/online-tools/sha256.html.
Similar to #1602.
=> tests: add tests for `SHA256`

Maths/test/SumOfGeometricProgression.test.js
This PR adds a test _covering_ this line:
https://github.com/TheAlgorithms/JavaScript/blob/10febce31a1623eebc3c81a99b9de2225963d62b/Maths/SumOfGeometricProgression.js#L26
=> test: add missing test for `SumOfGeometricProgression`

Maths/CoPrimeCheck.js, Maths/test/CoPrimeCheck.test.js
This PR _cleans-up_ the `CoPrimeCheck`:
- the error is now _thrown_,
- negative inputs are handled correctly.
=> fix: cleanup `CoPrimeCheck`

Maths/GetEuclidGCD.js, Maths/test/GetEuclidGCD.test.js
`GetEuclidGCD(0, 0)` is perfectly fine and it is `0`.
=> fix: `GetEuclidGCD(0, 0)` is `0`

String/CheckFlatCase.js, String/CheckKebabCase.js, String/CheckPascalCase.js, String/test/CheckCamelCase.test.js, String/test/CheckFlatCase.test.js, String/test/CheckKebabCase.test.js, String/test/CheckPascalCase.test.js
Errors should be thrown not returned. Additionally this PR adds _missing_ tests.
=> fix: throw error instead of returning it in check case type functions

Maths/CoPrimeCheck.js, Maths/test/CoPrimeCheck.test.js
Zeros are not properly handled in `CoPrimeCheck`. This PR fixes that and simplifies the implementation. It is a continuation of #1609 and #1621.
=> fix: handle zeros in `CoPrimeCheck`

Conversions/RailwayTimeConversion.js, Conversions/test/RailwayTimeConversion.test.js
=> fix: throw error instead of returning it `RailwayTimeConversion`

Maths/CheckKishnamurthyNumber.js, Maths/test/CheckKishnamurthyNumber.test.js
This PR:
- fixes `CheckKishnamurthyNumber` for `0`,
- makes `CheckKishnamurthyNumber` throw an error,
- adds tests.
=> fix: cleanup `CheckKishnamurthyNumber`

Conversions/DateDayDifference.js, Conversions/test/DateDayDiffernce.test.js
Currently `DateDayDifference('29/02/2024', '04/03/2024')` gives `5`. This PR fixes that. Further more:
- the errors now are _thrown_,
- the tests are reorganized; edited test cases were verified with the page linked in the docs,
- some minor refactoring was done.
=> fix: properly floor the partial results in `DateDayDifference`

.husky/pre-commit
Currently in [`pre-commit`](https://github.com/TheAlgorithms/JavaScript/blob/83b4dd82909badb19ad0a10e658ace64d69cd4da/.husky/pre-commit#L4) `npm run style` is used. This formats the files but the changes are not added to the commit (and the command is successful). I would suggest to use `npm run check-style`, which fill fail, if there are some files requiring reformatting. It fits to the logic behind `npm run test`.
=> chore: use `check-style` in

Maths/test/GetEuclidGCD.test.js
While working on #1645 I have discovered `'%o'`. I decided to use it here. It should have been done in #1642.
=> style: improve test names of `GetEuclidGCD`

Conversions/DateDayDifference.js, Conversions/DateToDay.js, Timing-Functions/ParseDate.js, Timing-Functions/test/ParseDate.test.js
As [promissed](https://github.com/TheAlgorithms/JavaScript/pull/1629#issuecomment-1977172066), this PR adds a function `parseDate`.
=> refactor: add and use `parseDate`

Recursive/FloodFill.js, Recursive/test/FloodFill.test.js
This PR reduced the _code duplication_ and adds missing tests.
=> refactor: reduce code duplication in `FloodFill`

Conversions/RailwayTimeConversion.js, Data-Structures/Array/Reverse.js, Data-Structures/Stack/Stack.js, Data-Structures/Tree/AVLTree.js, Data-Structures/Tree/BinarySearchTree.js, Data-Structures/Tree/Trie.js, Dynamic-Programming/NumberOfSubsetEqualToGivenSum.js, Project-Euler/Problem004.js
- [ ✅ ] Fix a bug or typo in an existing algorithm?
- [ ✅ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ✅ ] All new JavaScript files are placed inside an existing directory.
- [ ✅ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
- [ ✅ ] …
=> chore: convert functions to an ES2015 classes

.github/dependabot.yml, DIRECTORY.md
Auto-generates pull requests like:
* https://github.com/TheAlgorithms/Python/pulls?q=is%3Apr+author%3Aapp%2Fdependabot
* https://github.com/TheAlgorithms/Rust/pulls?q=is%3Apr+author%3Aapp%2Fdependabot
Fixes software supply chain safety warnings like at the bottom right of
https://github.com/TheAlgorithms/JavaScript/actions/runs/8960545794
* [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
* [Configuration options for the dependabot.yml file - package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)
---
[![Open in …
=> Keep GitHub Actions up to date with GitHub's Dependabot

Conversions/HexToDecimal.js, Conversions/test/HexToDecimal.test.js
This PR adds missing tests and handles _wrong_ inputs in `HexToDecimal`.
=> tests: add `HexToDecimal.test.js`

Dynamic-Programming/NumberOfSubsetEqualToGivenSum.js, Dynamic-Programming/tests/NumberOfSubsetEqualToGivenSum.test.js
I added tests for `NumberOfSubsetEqualToGivenSum`. The current implementation does not handle properly inputs less or equal `0`, so I decided to explicitly throw an error for such inputs.
=> test: add tests for `NumberOfSubsetEqualToGivenSum`

Backtracking/tests/RatInAMaze.test.js, Backtracking/tests/Sudoku.test.js, Data-Structures/Array/QuickSelect.js, Maths/test/EulerMethod.manual-test.js, Maths/test/FindMinIterator.test.js, Recursive/test/FloodFill.test.js
This PR removes some incode eslint warnings suppressions, which are redundant in my opinion.
=> style: remove redundant eslint suppressions

Project-Euler/Problem019.js, Project-Euler/test/Problem019.test.js
=> [Solution] Project euler challenge 19 with tests

.github/workflows/UploadCoverageReport.yml
Same as TheAlgorithms/Rust#670 - it contains the description of the problem.
Before merging, please add the token from https://app.codecov.io/gh/TheAlgorithms/JavaScript/settings as `CODECOV_TOKEN` into the repo secrets.
=> [DO NOT MERGE before adding the token] chore: update `codecov-action` to `v4`

Maths/AverageMean.js
what was wrong?
wrong array method in comment
Before:
```javascript
// This loop sums all values in the 'nums' array using forEach loop
const sum = nums.reduce((sum, cur) => sum + cur, 0)
```
After:
```javascript
// This calculates the sum of all values in the 'nums' array using reduce method.  
const sum = nums.reduce((sum, cur) => sum + cur, 0)
```
=> docs: fixed misleading comment about the array method (forEach instead of reduce) used in AverageMean.js

Search/LinearSearch.js, Search/test/LinearSearch.test.js
Added tests and Wikipedia reference for Linear Search Algo
=> test: added for Linear Search Algorithm

Data-Structures/Tree/BinarySearchTree.js, Data-Structures/Tree/test/BinarySearchTree.test.js
=> feat: add tests for binary search trees

DIRECTORY.md, Sliding-Windows/LongestSubarrayWithSumAtMost.js, Sliding-Windows/MaxSumSubarrayFixed.js, Sliding-Windows/test/LongestSubarrayWithSumAtMost.test.js, Sliding-Windows/test/MaxSumSubarrayFixed.test.js
Sliding Windows Algorithm
- Added maxSumSubarrayFixed function to calculate the maximum sum of a fixed-size subarray.
- Added longestSubarrayWithSumAtMost function to find the longest subarray with a sum less than or equal to a given target.
- Included tests for both functions to ensure correctness and edge case handling.
- Updated documentation to reflect the new implementations.
=> Implement sliding window algorithms for fixed and dynamic sizes with tests

Maths/AverageMean.js, Maths/test/AverageMean.test.js
This PR improves the `mean` function by:
- Adding input validation:
- Throws `TypeError` if input is not an array or contains non-number elements
- Throws `Error` if array is empty
- Adding a comprehensive test suite using `Vitest`, which includes:
- Empty arrays
- Invalid elements like `null`, `true`, `'string'`
- Floating-point numbers, negative values, large values
- Mixed integer and float arrays
The function now adheres more strictly to the expected behavior and is more robust against invalid input.
=> fix: improve mean function with input validation and extended tests

.codespellignore, .github/workflows/Ci.yml, .gitignore, Ciphers/KeyFinder.js, DIRECTORY.md, Data-Structures/Array/LocalMaximumPoint.js, Data-Structures/Array/test/LocalMaximumPoint.test.js, Data-Structures/Array/test/NumberOfLocalMaximumPoints.test.js, Data-Structures/Tree/SegmentTree.js, Dynamic-Programming/UniquePaths.js, Geometry/ConvexHullGraham.js, Graphs/Dijkstra.js, Maths/Abs.js, Maths/BinaryExponentiationIterative.js, Maths/EulersTotient.js, Maths/EulersTotientFunction.js, Maths/MatrixMultiplication.js, Maths/Polynomial.js, Maths/test/Pow.test.js, Search/UnionFind.js, String/AlphaNumericPalindrome.js, String/CheckPalindrome.js
=> chore: update spelling mistakes
