TheAlgorithms/JavaScript

Sorts/insertionSort.js
Added Implementation of Insertion Sort
=> Added Implementation of Insertion Sort

Sorts/quickSort.js
Added the implementation of the quicksort algorithm.
=> Added quicksort to the sorting algorithms.

Sorts/bogoSort.js
Added the implementation of the bogosort algorithm.
=> Added Bogosort algorithm

Sorts/heapSort.js
Added the implementation of the heap sort algorithm.
=> Added heapsort algorithm.

Sorts/gnomeSort.js
=> Implemented gnome sort algorithm

Sorts/shellSort.js
=> Implemented shell sort algorithm

Data Structures/Stack/Stack.js
I had wrote the stack with prototype notation. This is safer.
=> wrote prototype notation

Data Structures/Queue/Queue.js
Wrote the Queue more object oriented.
=> Changed queue

linear-algebra-javascript/README.md, linear-algebra-javascript/package-lock.json, linear-algebra-javascript/package.json, linear-algebra-javascript/src/la_lib.js, linear-algebra-javascript/src/la_lib.ts, linear-algebra-javascript/test/test.js
I added a linear algebra library.
=> Added a linear algebra library

Sorts/flashSort.js
Fixes #62 
Added Declaration for Local Variable in Flash Sort
=> Fixes#62 : Added Declaration for Local Variable

Sorts/cycleSort.js
=> Implemented cycle sort algorithm

Data Structures/Graph/Graph.js
A simple Graph Data structure implementation using adjacency list 
an infrastructure  for implementing BFS DFS and other Graph Algorithms
=> adding Graph data structure

Hashes/SHA1.js, Hashes/SHA256.js
Implemented the SHA-1 and SHA-256 hashing algorithms in Javascript.
=> Added SHA-1 and SHA-256 hashing algorithms

README.md, Search/jumpSearch.js
#14
I added Jump Search algorithm, I hope everything is good and it gets merged, if not please let me know what changes I need to make 
Thank you
=> Jump Search Algorithm

Sorts/bucketSort.js
This fixes a [recommendation on lgtm](https://lgtm.com/projects/g/TheAlgorithms/Javascript/snapshot/9fe2ca0492e0813c5e5486498c6b53a00c4a61e3/files/Sorts/bucketSort.js?sort=name&dir=ASC&mode=heatmap)
=> Added Semicolon to Avoid Auto Semicolon Insertion

Algorithms/KadaneAlgo.js
I am adding Kadane Algorithms which is used to solve the **Maximum Subarray Problem**, under O(n) time complexity.
=> Kadane Algo is added

DIRECTORY.md, Data Structures/Linked List/DoublyLinkedList.js
i added a doubly-linked-list function to the linked list directory!
=> Add doublylinkedlist

Ciphers/keyFinder.js, Ciphers/vigenereCipher.js, Conversions/DecimalToHex.js, Data Structures/Heap/MinPriorityQueue.js, Data Structures/Linked List/DoublyLinkedList.js, Data Structures/Queue/Queue.js, Data Structures/Stack/Stack.js, Data Structures/Tree/Binary Search Tree.js
Resolve some of the topics in #139
=> Fixing non compliant files (Ciphers, Conversions and Data Structures)

maths/abs.js
=> abs.js: abs_val() --> absVal() for standardjs

maths/find_lcm.js
=> find_lcm.js: Standardjs fixes

Data Structures/Queue/QueueUsing2Stacks.js
clear and simple implementation of a queue using 2 stacks useful for student of Data structures and algorithms.
=> adding an implementation of a queue using 2 stacks

String/ReverseWords.js
=> Add reverse words

.github/pull_request_template.md
=> JavaScript, not Javascript

Data-Structures/Array/QuickSelect.js, Sorts/BubbleSort.js, Sorts/CocktailShakerSort.js, Sorts/CombSort.js, Sorts/GnomeSort.js, Sorts/Heapsort.js, Sorts/SelectionSort.js
=> feat: adjust swap grammar

Dynamic-Programming/KadaneAlgo.js
compare maxSum with cummulativeSum only when cummulativeSum is greater than zero
Optimized maxSum, cummulativeSum comparision
* [] All new JavaScript files are placed inside an existing directory.
* [] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
* [] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.
=> Optimizing maxSum updation

Dynamic-Programming/MaxNonAdjacentSum.js
=> Added max non adjacent sum

Maths/PiApproximationMonteCarlo.js
=> Added Monte Carlo Pi Approximation

back-tracking/Sudoku.js
=> Added backtracking (sudoku)

Conversions/DecimalToHex.js
Push should be converted to hexout. unshift
=> I found a mistake

back-tracking/NQueen.js
=> Added n-queen

back-tracking/KnightTour.js
=> Added Open Knight Tour Algorithm

Cache/LFUCache.js
=> Added LFU Cache

Graphs/ConnectedComponents.js
=> Added Connected Components using DFS

Graphs/PrimMST.js
=> Added Prim's Algoritm

Graphs/DepthFirstSearchRecursive.js
=> Added DFS (Recursive) - Graph

Graphs/DepthFirstSearchIterative.js
=> Added DFS (Iterative) - Graph

Graphs/BreadthFirstSearch.js
=> Added BFS (Graph)

Graphs/KruskalMST.js
=> Added Kruskal's Algorithm

Data-Structures/Stack/Stack.js
=> fixed issue with delete operator on stacks

Search/ExponentialSearch.js, Search/InterpolationSearch.js
=> Added Interpolation and exponential search 

DIRECTORY.md, Sorts/IntroSort.js
* [] Fix a bug or typo in an existing algorithm?
* [] Documentation change?
=> Added Introsort Implementation in JS.

String/PatternMatching.js
Added a string pattern matching algorithm to the string package
=> Added string pattern matching algorithm

Dynamic-Programming/LevenshteinDistance.js
=> Added Levenshtein Distance Algorithm

Dynamic-Programming/Knapsack.js
=> Adden Knapsack Problem Algorithm

Dynamic-Programming/CoinChange.js
=> Added CoinChange Algorithm

Dynamic-Programming/EggDropping.js
=> Added Egg Dropping Puzzle Algorithm

String/CheckAnagram.js
…nagrams
* [✔ ] Add an algorithm?
* [✔ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ ✔] This pull request is all my own work -- I have not plagiarized.
* [✔ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ✔] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [✔ ] All new JavaScript files are placed inside an existing directory.
* [ ✔] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
* [✔ ] All new algorithms have a URL in its comments that points to …
=> Add string check anagram

Conversions/DecimalToOctal.js
Moved 1 liner code into 2 lines.
###
* [ ✓] Changed a keyword to match the project guidelines and moved a one liner into two lines.
* [✓ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [✓ ] This pull request is all my own work -- I have not plagiarized.
* [✓ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ✓] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
=> Changed “var” to “let” in DecimalToOctal.js

Data-Structures/Stack/StackES6.js
* [ *] Add an algorithm?
* [* ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [* ] This pull request is all my own work -- I have not plagiarized.
* [* ] I know that pull requests will not be merged if they fail the automated tests.
* [* ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [* ] All new JavaScript files are placed inside an existing directory.
* [ *] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
* [ *] All new algorithms have a URL in its comments that points to Wikipedia or …
=> new stack implementation (ES6) fixes: #{246}

Graphs/DijkstraSmallestPath.js
=> Changed var to const/let

Maths/digitSum.js
=> digitSumAdded

Maths/ModularBinaryExponentiationRecursive.js
Added Modular Binary Exponentiation (Recursive)
=> Added Modular Binary Exponentiation (Recursive)

DIRECTORY.md, Data-Structures/Tree/Trie.js
* [] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.
=> Trie Added in JS

Recursive/TowerOfHanoi.js
=> Tower of Hanoi added to recursive

Maths/ReversePolishNotation.js
=> Reverse polish notation

Search/StringSearch.js
=> Added StringSearch

Search/FibonacciSearch.js
Implemented Fibonacci Search algorithm using JavaScript
* [x ] Add an algorithm?
* [x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x ] This pull request is all my own work -- I have not plagiarized.
* [x ] I know that pull requests will not be merged if they fail the automated tests.
* [x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x ] All new JavaScript files are placed inside an existing directory.
* [x ] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
* [x ] All new algorithms …
=> Implemented FibonacciSearch Using JavaScript

Maths/AverageMean.js
=> Improved Documentation

String/CheckAnagram.js
Just change the output string, make sure it's the same.
* [ x ] Fix a bug or typo in an existing algorithm?
* [ x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ x ] This pull request is all my own work -- I have not plagiarized.
* [ x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
=> tweak: must be same output string

Maths/MeanSquareError.js
=> Added Mean Square Error

Conversions/BinaryToDecimal.js
=> Fix methodname and parameter type in BinaryToDecimal.js

Linear-Algebra/test/test.js, String/CheckWordOccurrence.js, String/CheckWordOcurrence.test.js, package-lock.json, package.json
=> Added new algoritm

Maths/isDivisible.js
=> Added isDivisble.js

Dynamic-Programming/MinimumCostPath.js
=> Added Minimum Cost Path Algorithm

Project-Euler/Problem2.js
=> feat: Added O(1) Sum of Even Terms of Fibonacci Series Algorithm

Dynamic-Programming/LongestPalindromicSubsequence.js
=> Added Longest Palindromic subsequence

Maths/Area.js, Maths/Area.test.js
=> Added new area calculators

String/CheckVowels.js, String/CheckVowels.test.js
=> Add check vowels algorithm

Conversions/RGBToHex.js
=> Add RGBToHex

String/FormatPhoneNumber.js, String/FormatPhoneNumber.test.js
=> Add Phone Number Formatting Function

String/MaxCharacter.js, String/MaxCharacter.test.js
=> Added max character algorithm

String/PermutateString.js, String/PermutateString.test.js
Implementing String Permutation Algorithm.
See #14 
=> Add Algorithm String Permutation

Recursive/BinarySearch.js
=> binary search recursive algorithm added

String/ValidateEmail.js, String/ValidateEmail.test.js
=> Add Email Validation Function

Ciphers/ROT13.js
=> Add ROT13 cipher

Maths/isOdd.js
* [X ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ X] I know that pull requests will not be merged if they fail the automated tests.
* [ X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ X] All new JavaScript files are placed inside an existing directory.
* [ X] All new algorithms have a URL in its comments that points to Wikipedia or …
=> Added isOdd function.

Graphs/NumberOfIslands.js
* [ x ] Add an algorithm?
* [ x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ x ] This pull request is all my own work -- I have not plagiarized.
* [ x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x ] All new JavaScript files are placed inside an existing directory.
* [ x ] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
* [ x ] All new algorithms have a URL in its comments that points to Wikipedia …
=> Number of islands

Project-Euler/Problem1.js, Project-Euler/Problem2.js, package-lock.json
1) Was not ES6-syntax
2) Had a bug in the code where it calculated the number including, rather up to
3) Fixed to allow input when code is run
* [n/a] All new JavaScript files are placed inside an existing directory.
* [] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.
Relates to: #14
=> Fix Euler Problem 1

Project-Euler/Problem6.js
Adds code for Euler Problem 6.
Relates to: #14
=> Euler Problem 6

Project-Euler/Problem7.js
Added solution for Euler Problem 7.
Relates to: #14
=> Euler Problem 7

String/CheckPangram.js, String/test/CheckPangram.test.js
Added check pangram algorithm implementation
Relates to #14
=> Add check pangram algorithm

Maths/test/Area.test.js
=> move math-area tests to test folder

Project-Euler/Problem3.js
=> Fix Euler Problem 3

Sorts/MergeSort.js, Sorts/QuickSort.js
=> Add doctest for QuickSort and MergeSort

Project-Euler/Problem4.js
=> feat: Added Solution to Euler Problem 4

Navigation/Haversine.js, Navigation/Haversine.test.js
=> Added the Haversine distance algoritm

DIRECTORY.md, Maths/Softmax.js, Maths/test/Softmax.test.js
=> Added Softmax to Maths folder

Maths/WhileLoopFactorial.js
=> Added while loop factorial

.github/workflows/nodejs.yml, DIRECTORY.md
=> GitHub Action: Add mocha Maths/test/Abs.test.js

Data-Structures/Queue/Queue.js
=> change from ES5 to ES6

Maths/BinaryConvert.js, Maths/test/BInaryConvert.test.js, package-lock.json
add convert number to binary number
=> add  binary convert

Maths/Fibonacci.js, Maths/test/Fibonacci.test.js
=> Add O(log n) algorithm using matrix exponentiation to find n-th fibonacci

DIRECTORY.md, Maths/PermutationAndCombination.js
=> Implementing Permutations and Combinations

Sorts/CocktailShakerSort.js
- Improved Comments and Formatting.
- The function in CocktailShakerSort was not returning the array. Changed that.
- Improved the Implementation Examples and Console logs.
- And Finally, added doctests as mentioned in ([Issue #142](https://github.com/TheAlgorithms/Javascript/issues/142))
=> Improved CocktailShakerSort and added Doctests

Maths/Pow.js, Maths/test/Pow.test.js
=> Add Pow.js

Maths/Fibonacci.js, Maths/test/Fibonacci.test.js
=> Add extra testcases for Fibonacci and improve code

String/KMPPatternSearching.js, String/test/KMPPatternSearching.test.js
=> Add KMP pattern searching algorithm (Fixes #518)

Sorts/BeadSort.js
- Improved Description, Comments and Formatting.
- Improved the Implementation Examples and Console logs.
=> Improved Bead Sort representation

Graphs/NodeNeighbors.js
* [v] Add an algorithm?
* [v] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [v] This pull request is all my own work -- I have not plagiarized.
* [v] I know that pull requests will not be merged if they fail the automated tests.
* [v] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [v] All new JavaScript files are placed inside an existing directory.
* [v] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames. …
=> Node Neighbors

String/ReverseWords.js
=> #142 #461 Adding Doctests to String/ReverseWords.js

Graphs/Density.js
* [v] Add an algorithm?
* [v] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [v] This pull request is all my own work -- I have not plagiarized.
* [v] I know that pull requests will not be merged if they fail the automated tests.
* [v] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [v] All new JavaScript files are placed inside an existing directory.
* [v] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames. …
=> Added density calculation

Conversions/ArbitraryBase.js
=> Added implementation for arbitrary base conversion

Maths/EulersTotientFunction.js
* [-] Fix a bug or typo in an existing algorithm?
=> Fix grammar.

Maths/ArmstrongNumber.js
=> Correct algorithm definition  | ArmstrongNumber

Graphs/BreadthFirstSearch.js
=> add algorithm Breadth-first search

Graphs/BreadthFirstShortestPath.js
=> Add algorithm Breadth-first shortest path

Cellular-Automata/ConwaysGameOfLife.js
Conway's Game of Life, implementation adapted from https://github.com/TheAlgorithms/Python/blob/master/cellular_automata/conways_game_of_life.py
=> Added Conways game of life

Sorts/FindSecondLargestElement.js, Sorts/FindSecondLargestSort.js
* [ x ] Add an algorithm?
* [ x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ x ] This pull request is all my own work -- I have not plagiarized.
* [ x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x ] All new JavaScript files are placed inside an existing directory.
* [ x ] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
* [ x ] All new algorithms have a URL in its comments that points to Wikipedia …
=> Add FindSecondLargestSort

Maths/Mandelbrot.js
=> Add algorithm for the Mandelbrot set 

Recursive/KochSnowflake.js
=> Add Koch snowflake

String/CreatePermutations.js, String/test/CreatePermutations.test.js
* [] Add an algorithm?
* [] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
=> Added test script for CreatePermutations and file name change

Maths/SquareRoot.js
=> Added `sqrt()` function

Project-Euler/Problem10.js, Project-Euler/test/Problem10.test.js, String/CreatePermutations.js, String/test/CreatePermutations.test.js
=> Project euler problem 10

Sorts/MergeSort.js
=> fixed the merge implementation in MergeSort

Geometry/ConvexHullGraham.js, package.json
I have also made a new directory(Geometry) for the respective algorithm.
=> Implemented  ConvexHull using Graham Scan 

Data-Structures/Queue/CircularQueue.js
Adding an algorithm for circular queue
=> Add Circular Queue

Maths/MatrixExponentiationRecursive.js
=> Added Matrix Exponentiation (Recursive)

Ciphers/KeywordShiftedAlphabet.js
Adding new Cipher > Keyword shifted alphabet
=> Cipher keyword shifted alphabet

Maths/SieveOfEratosthenes.js
=> Improved SieveOfEratosthenes.js

Graphs/FloydWarshall.js
=> Added FloydWarshall All Pairs Shortest Path Algo

Maths/EulersTotient.js
Added Euler's Totient Function
=> Added EulersTotient

Maths/PrimeFactors.js
=> Added PrimeFactors

Maths/BinaryExponentiationRecursive.js
Added Binary Exponentiation (Recursive)
=> Added Binary Exponentiation (Recursive)

Search/BinarySearch.js
* BinarySearchIterative Function is added
* BinarySearch function is renamed to BinarySearchRecurisve
* changes in test function
- 3 binarySearchRecursive tests
- 3 binarySearchIterative tests
=> Added BinarySearchIterative Function

Sorts/OddEvenSort.js
=> OddEvenSort Added

Recursive/FloodFill.js
=> add flood fill 

CONTRIBUTING.md
=> Fix some typos in CONTRIBUTING.md

Sorts/CountingSort.js
=> Fixed the missing arguments in the countingSort() function call

Maths/IsEven.js, Maths/test/IsEven.test.js
=> Added IsEven Function to Maths directory

Maths/DegreeToRadian.js, Maths/test/DegreeToRadian.test.js
* [ X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ X] I know that pull requests will not be merged if they fail the automated tests.
* [ X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ X] All new JavaScript files are placed inside an existing directory. …
=> Added DegreeToRadian.js and DegreeToRadian.test.js in Maths directory

Maths/RadianToDegree.js, Maths/test/RadianToDegree.test.js
* [ X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ X] I know that pull requests will not be merged if they fail the automated tests.
* [ X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ X] All new JavaScript files are placed inside an existing directory. …
=> Added RadianToDegree.js and RadianToDegree.test.js in Maths directory

String/HammingDistance.js, String/test/HammingDistance.test.js
* [ X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ X] I know that pull requests will not be merged if they fail the automated tests.
* [ X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ X] All new JavaScript files are placed inside an existing directory. …
=> Added HammingDistance.js and HammingDistance.test.js in String directory

Maths/AverageMedian.js, Maths/test/AverageMedian.test.js
* Add an algorithm?
* I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* This pull request is all my own work -- I have not plagiarized.
* I know that pull requests will not be merged if they fail the automated tests.
* This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* All new JavaScript files are placed inside an existing directory.
* All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames. …
=> Added averageMedian function

Maths/FareyApproximation.js, Maths/test/FareyApproximation.test.js
=> Add Farey Approximation Algorithm

Maths/Volume.js
* [v] Add an algorithm?
* [v] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [v] This pull request is all my own work -- I have not plagiarized.
* [v] I know that pull requests will not be merged if they fail the automated tests.
* [v] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [v] All new JavaScript files are placed inside an existing directory.
* [v] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames. …
=> Added Volume.js into the Math file

Maths/Volume.js, Maths/test/Volume.test.js
Volume.test.js file is to test on the calculations for the Volume.js file.
* [v] Add an algorithm?
* [v ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [v ] This pull request is all my own work -- I have not plagiarized.
* [v ] I know that pull requests will not be merged if they fail the automated tests.
* [v ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [v ] All new JavaScript files are placed inside an existing directory.
* [v ] All filenames should use the UpperCamelCase (PascalCase) style.  There should …
=> Added Volume.test.js file

Recursive/SubsequenceRecursive.js
Added a new JS file under Recursion folder names subsequenceRecursive.js. 
- Finding subsequence using recursion is an important problem, so it was vital to add this algorithm.
- Some insights of this algorithm:
- It gives lexicographically ordered subsequences.
- It gives distinct subsequences.
=> added subsequenceRecursive.js file under Recursion

Backtracking/GeneratePermutations.js
Added an important algorithm "GeneratePermutations" in Backtracking.
Key points of this algorithm:
- It gives distinct permutations
- It gives permutations in sorted manner
=> added GeneratePermutations in Backtracking

Recursive/BinaryEquivalent.js
Added an algorithm that finds the binary equivalent of a number using recursion.
=> added BinaryEquivalent file in Recursive

String/CheckCamelCase.js, String/CheckPascalCase.js
=> CheckCamelCase and CheckPascalCase method added to String category

String/CheckFlatCase.js, String/CheckKebabCase.js, String/CheckSnakeCase.js
=> Added CheckFlatCase, CheckSnakeCase, CheckKebabCase methods.

Backtracking/RatInAMaze.js
Added RatInAMaze in Backtracking. This is one of the main problems for backtracking.
=> RatInAMaze added in Backtracking

Conversions/DateDayDifference.js
=> added DateDayDifference method in Conversions category

Conversions/TitleCaseConversion.js
=> added TitleCaseConversion method in conversion category

Maths/GetEuclidGCD.js, Maths/GetGCD.js, Maths/ReverseNumber.js
=> Added GetGCD and ReverseNumber method in Maths category.

Conversions/RailwayTimeConversion.js
=> added RailwayTimeConversion method in the conversion category.

Maths/CheckKishnamurthyNumber.js, Maths/CoPrimeCheck.js
=> added CoPrimeCheck and CheckKishnamurthyNumber methods

DIRECTORY.md, String/CheckFlatCase.js, String/test/CheckFlatCase.test.js
- Created a test file and added tests for `CheckFlatCase.js`
- Updated the documentation with an explanation of what flat case is
- Updated names/types to align with js conventions 
=> Tests for check flat case

Sorts/QuickSortRecursive.js, Sorts/QuickSortRecursive.test.js
=> add QuickSortRecursive method.

String/CheckVowels.test.js
Adds additional tests to CheckVowels to cover additional inputs and edge cases.
*[x] Add tests 
=> Tests check vowels

README.md
=> added standard js badge in Readme.md

String/CheckAnagram.js, String/test/CheckAnagram.test.js
Add additional test cases to CheckAnagrams to include expanded inputs and edge cases.
* [x ] Add tests?
=> Tests check anagrams

String/CheckSnakeCase.js, String/test/CheckSnakeCase.test.js
- Add tests to checkSnakeCase algorithm
- Change function name in order to respect JavaScript coding conventions
- Use ES6 export
=> Add tests for snake case algorithm

Conversions/DecimalToRoman.js, Conversions/test/DecimalToRoman.test.js
I find that repo has `romanToDecimal` but not `decimalToRoman` so I create one
=> Added DecimalToRoman

Conversions/DecimalToHex.js, Conversions/test/DecimalToHex.test.js
- Add test file DecimalToHex.test.js
- Add export to DecimalToHex.js
- Remove console.log from DecimalToHex.js
=> DecimalToHex - test

String/ScrambleStrings.js
=> feat: add scramble string algorithm

Sorts/FisherYatesShuffle.js, Sorts/test/FisherYatesShuffle.test.js
Hi 👋
I'd like to make my contribution as part of **Hacktoberfest'21**
I offer you the Fisher-Yates algorithm to mix arrays
I also pushed unit tests for this
If it's good for you, could you add the `hacktoberfest-accepted` label? 🙏
=> Added Fisher Yates Algorithm

Dynamic-Programming/LongestPalindromicSubsequence.js, Dynamic-Programming/tests/LongestPalindromicSubsequence.test.js
=> Added test cases for LongestPalindromicSubsequence

Dynamic-Programming/LongestValidParentheses.js, Dynamic-Programming/tests/LongestValidParentheses.test.js
=> Added test cases for LongestValidParentheses

Dynamic-Programming/TrappingRainWater.js, Dynamic-Programming/tests/TrappingRainWater.test.js
=> Added test cases for TrappingRainWater

README.md
Documentation changes:
In the `README.md` file, I have capitalize the first letter. Kindly accept pull request. 
Thank you
=> capitalize first letter

Data-Structures/Tree/Trie.js, Dynamic-Programming/SudokuSolver.js
=> fixed the issue in Trie file and typo in sudoku

Conversions/UpperCaseConversion.js, Conversions/test/UpperCaseConverstion.test.js
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/) 
=> Upper case conversion tests

Maths/LinearSieve.js, Maths/test/LinearSieve.test.js
=> Add LinearSieve.js

Dynamic-Programming/SudokuSolver.js
=> fixed argument data type

Maths/PowLogarithmic.js, Maths/test/PowLogarithmic.test.js
=> Add PowLogarithmic in Math

Dynamic-Programming/TribonacciNumber.js, Dynamic-Programming/tests/TribonacciNumber.test.js
=> Add TribonacciNumber in dp

Dynamic-Programming/FibonacciNumber.js, Dynamic-Programming/tests/FibonacciNumber.test.js
=> Add FibonacciNumber.js test case and update the decription of function.

Dynamic-Programming/SieveOfEratosthenes.js, Dynamic-Programming/tests/SieveOfEratosthenes.test.js
=> optamization, documantation, change return Array[bool] => Array[primes only], Add test case 

Recursive/BinarySearch.js, Recursive/test/BinarySearch.test.js
=> Add test cases, optamization of code, and Add description of function

Maths/FindMin.js, Maths/test/FindMin.test.js
=> Add FindMin

Data-Structures/Graph/Graph.js
=> Modify Graph bfs method

Recursive/FibonacciNumberRecursive.js, Recursive/test/FibonacciNumberRecursive.test.js
=> Add test cases

String/AlphaNumericPalindrome.js
=> alphaNumericPlaindrome optamization

String/ValidateUrl.js, String/test/ValidateUrl.test.js
=> Add ValidateUrl in String

Dynamic-Programming/Sliding-Window/PermutationinString.js
=> Remove console.log from Permutation String algorithm

Dynamic-Programming/LongestCommonSubsequence.js, Dynamic-Programming/tests/LongestCommonSubsequence.test.js
Adds tests and docs as well as refactors the Longest Common Subsequence algorithm
=> Add tests and docs for the Longest Common Subsequence algorithm

Maths/Area.js, Maths/test/Area.test.js
=> add areaTriangleWithAllThreeSides method in Math/Area.js

Data-Structures/Linked-List/AddTwoNumbers.js, Data-Structures/Linked-List/SinglyLinkedList.js, Data-Structures/Linked-List/test/AddTwoNumbers.test.js
=> Implement Add Two Numbers (Linked List)

Data-Structures/Linked-List/DoublyLinkedList.js
=> replaced constructor function with es6 class syntax

Maths/IsOdd.js, Maths/test/IsOdd.test.js
=> Improved `IsOdd` function

String/Upper.js
=> Added replace method to `Upper`

Bit-Manipulation/test/BinaryCountSetBits.test.js
- [✅] Add a test case?
- [✅] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [✅] This pull request is all my own work -- I have not plagiarized.
- [✅] I know that pull requests will not be merged if they fail the automated tests.
- [✅] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [✅] All new JavaScript files are placed inside an existing directory.
- [✅] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames. …
=> Add testcases of BinaryCountSetBits function

Maths/test/SquareRoot.test.js
- [✅] Add test case?
- [✅] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [✅] This pull request is all my own work -- I have not plagiarized.
- [✅] I know that pull requests will not be merged if they fail the automated tests.
- [✅] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [✅] All new JavaScript files are placed inside an existing directory.
- [✅] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames. …
=> Add test case of SquareRoot function

Conversions/test/ArbitraryBase.test.js, Conversions/test/DateDayDiffernce.test.js, Conversions/test/DateToDay.test.js
=> Add test cases to ArbitraryBase, DateToDay & DateDayDifference Algorithm

Maths/FindMinIterator.js, Maths/test/FindMinIterator.test.js
This is the renamed `FindMin` to `FindMinIterator` by @RuSaG0 
Closes #870 
Do the `standard` thing.
Rename `FindMin` to `FindMinIterator`
Rename to `FindMinIterator`
Pull `FindMin` from `master`
=> Add FindMinIterator algorithm

package-lock.json, package.json
=> added @babel/eslint-parser

Conversions/test/RGBToHex.test.js, Conversions/test/RailwayTimeConversion.test.js
- [ ✅] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames. …
=> Add test case to RGBToHex & RailwayTimeConversion algorithm

Cache/LFUCache.js, Cache/test/LFUCache.test.js
=> Added new clean `LFUCache` class

String/CheckExceeding.js, String/test/CheckExceeding.test.js
=> Add `CheckExceeding` function

Sorts/test/FlashSort.test.js
- [ ✅ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ✅ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames. …
=> Add test case to FlashSort algorithm

Sorts/test/HeapSort.test.js
- [ ✅ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ✅ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames. …
=> Add test case to HeapSort Algorithm

Sorts/OddEvenSort.js, Sorts/test/OddEvenSort.test.js
=> Add test case and fix the OddEvenSort Algorithm

Ciphers/test/Atbash.test.js
To test if the algorithm actually works, it should both encode and decode.
- fix the test description
=> Round-trip testing for Atbash cipher

package-lock.json, package.json
=> Added jest type for suggestions

String/ReverseWords.js, String/test/ReverseWords.test.js
=> Replaced by `reduceRight` & `trim` method

Ciphers/Atbash.js
=> Cache repeated function calls

Ciphers/Atbash.js, Ciphers/CaesarsCipher.js, Ciphers/test/CaesarsCipher.test.js
=> Improved `CaesarsCipher` Algorithm

Sorts/test/RadixSort.test.js
- [✅  ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [✅  ] This pull request is all my own work -- I have not plagiarized.
- [✅  ] I know that pull requests will not be merged if they fail the automated tests. …
=> Add test case to radixSort Algorithm

Sorts/PigeonHoleSort.js, Sorts/test/pigeonHoleSort.test.js
- [ ✅] Fix a bug or typo in an existing algorithm? …
=> Add test case and fix pigeonHoleSort Algorithm

Sorts/test/ShellSort.test.js
=> Add test case to shellSort algorithm

Sorts/TimSort.js, Sorts/test/TimSort.test.js
- [✅ ] Fix a bug or typo in an existing algorithm?
- [ ✅] I know that pull requests will not be merged if they fail the automated tests. …
=> Add test case and fix TimSort algo

DIRECTORY.md, Data-Structures/Tree/Trie.js, Maths/test/EulerMethod.manual-test.js, Sorts/TopologicalSort.js
=> Format codebase with `standard.js`

Maths/test/GetEuclidGCD.test.js
test was not present beforehand.
=> EuclidGCD: add tests

Sorts/StoogeSort.js, Sorts/test/StoogeSort.test.js
=> Add the Stooge Sort Algorithm

Ciphers/test/KeywordShiftedAlphabet.test.js
- [ ✅] Add Testcase
- [ ✅] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames. …
=> Add test case to KeywordShiftedAlphabet algorithm

String/FormatPhoneNumber.js, String/test/FormatPhoneNumber.test.js
=> Removed useless execution

Ciphers/test/VigenereCipher.test.js
- [✅  ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [✅  ] This pull request is all my own work -- I have not plagiarized.
- [✅  ] I know that pull requests will not be merged if they fail the automated tests. …
=> Add test case to Vigenere Cipher Algorithm

Conversions/test/HexToRGB.test.js
- [ ✅ ] I know that pull requests will not be merged if they fail the automated tests. …
=> Add test case to HexToRGB algorithm

Maths/TwinPrime.js, Maths/test/TwinPrime.test.js
=> Add Twin Primes algorithm

Sorts/test/FindSecondLargestElement.test.js
- [✅  ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [✅  ] This pull request is all my own work -- I have not plagiarized.
- [✅  ] I know that pull requests will not be merged if they fail the automated tests. …
=> Add test case to Find Second Largest Element Algorithm

String/IsPalindrome.js, String/test/IsPalindrome.test.js
=> Add new IsPalindrome implementation

Ciphers/AffineCipher.js, Ciphers/test/AffineCipher.test.js
=> Add Affine Cipher

DIRECTORY.md, Maths/GetEuclidGCD.js
* Fix GetEuclidGCD
Implement the actual Euclidean Algorithm
* Replace == with ===
* Lua > JS
* Standard sucks
* Oops
* Update GetEuclidGCD.js
* Updated Documentation in README.md
Co-authored-by: github-actions <${GITHUB_ACTOR}@users.noreply.github.com>
=> merge: Fix GetEuclidGCD (#1068)

Ciphers/AffineCipher.js, Ciphers/test/AffineCipher.test.js
- encrypt func should return alphabet instead of numbers string
- add checking for coprime as if coefficient 'a' is not coprime to 26 will reusultant in invalid result in inverse mod
- modify some test case 
=> Fix Affine-Cipher encrypt and drypt func

.github/workflows/Ci.yml, DIRECTORY.md, Maths/PiApproximationMonteCarlo.js, String/CheckAnagram.js
See the commit list for more information.
=> fix: spellings which are making ci fail

Maths/MobiusFunction.js, Maths/test/MobiusFunction.test.js
=> algorithm: mobius function implementation

Maths/BinomialCoefficient.js, Maths/test/BinomialCoefficient.test.js
=> Binomial coefficient implementation

Maths/LiouvilleFunction.js, Maths/test/LiouvilleFunction.test.js
=> algorithm: Liouville function

DIRECTORY.md, String/FirstUniqueCharacter.js, String/test/FirstUniqueCharacter.test.js
=> algorithm: first unique char in a string

Dynamic-Programming/tests/ZeroOneKnapsack.test.js
=> tests: Zero One Knapsack

String/test/BoyerMoore.test.js
=> tests: Boyer Moore Algorithm

CONTRIBUTING.md, package-lock.json, package.json
…d test some codes and i found out that i needed to run and install jest from npm first, i did and it worked
=> chore: add instruction for installing dependencies

Search/TernarySearch.js
=> fix: grammar mistakes in JSDoc

Bit-Manipulation/BinaryCountSetBits.js, Bit-Manipulation/test/BinaryCountSetBits.test.js
=> chore: check for non-integer types in bit count

.github/workflows/Ci.yml
Upgrade `actions/checkout` and `actions/setup-node` to v3.
=> dependencies: upgrade to checkout v3

Bit-Manipulation/LogTwo.js, Bit-Manipulation/test/LogTwo.test.js
=> algorithm: Log2 using bitwise operations

Dynamic-Programming/CatalanNumbers.js, Dynamic-Programming/tests/CatalanNumbers.test.js
=> algorithm: catalan numbers

Maths/MeanAbsoluteDeviation.js, Maths/test/MeanAbsoluteDeviation.test.js
=> Add an algorithm to find mean absolute deviation

Project-Euler/Problem017.js, Project-Euler/test/Problem017.test.js
=> :sparkles: Project Euler Problem 17

Sorts/SwapSort.js, Sorts/test/SwapSort.test.js
=> Swapsort algorithm and corresponding tests

Maths/isPalindromeIntegerNumber.js, Maths/test/isPalindromeIntegerNumber.test.js, String/IsPalindrome.js
=> algorithm: check if integer is palindrome

Maths/CountNumbersDivisible.js, Maths/test/CountNumbersDivisible.test.js
=> algorithm: count the numbers divisible by ‘M’ in a given range

Maths/CollatzSequence.js, Sorts/BinaryInsertionSort.js, Sorts/test/BinaryInsertionSort.test.js
- [] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
=> algorithm: binary insertion sort

README.md
A discord link in Readme.md was updated to the new link to discord invites, namely "https://the-algorithms.com/discord/"
=> Updates Discord Invite Link

.gitpod.yml, DIRECTORY.md
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1203"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: improve the Gitpod file

Maths/SieveOfEratosthenesIntArray.js, Maths/test/SieveOfEratosthenesIntArray.test.js
This algorithm is a distinct implementation of the current sieve in the repo because this returns an array of integers that only contain prime numbers.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1205"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: sieve

Data-Structures/Tree/SegmentTree.js, Data-Structures/Tree/test/SegmentTree.test.js
=> algorithm: SegmentTree

DIRECTORY.md, Dynamic-Programming/UniquePaths.js, Dynamic-Programming/tests/UniquePaths.test.js
`This Problem is the most common pattern of Dynamic Programming`
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1211"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: unique paths

Graphs/Kosaraju.js, Graphs/test/Kosaraju.test.js, package-lock.json
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1215"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: kosaraju

Maths/FindLcm.js, Maths/test/FindLcm.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1222"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> enhancement: FindLCM algorithm

Graphs/BreadthFirstSearch.js
Use repo's Queue instead of list in the Breadth First Search implementation, see #758
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1228"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: use internal queue definition in BFS

Graphs/BreadthFirstShortestPath.js
Use repo's implementation of Queue in `BreadthFirstShortestPath.js`, see #758 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1230"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: use internal queue definition in BFS Shortest Path

Graphs/BinaryLifting.js, Graphs/test/BinaryLifting.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1218"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: binary lifting

Conversions/LitersToUSGallons.js, Conversions/test/LitersToUSGallons.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1255"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> conversion: liters to US gallons

Conversions/LitersToImperialGallons.js, Conversions/test/LitersToImperialGallons.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1256"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> conversion: liters to imperial gallons

Dynamic-Programming/UniquePaths2.js, Dynamic-Programming/tests/UniquePaths2.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1257"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: unique paths 2

String/PercentageOfLetters.js, String/test/PercentageOfLetters.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1261"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: percentage of letter

Maths/HexagonalNumber.js, Maths/test/HexagonalNumber.test.js
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1265"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> algorithm: Hexagonal number

README.md
Fixed some typos in README.
- [ X] Documentation change?
- [X ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [ X] This pull request is all my own work -- I have not plagiarized.
- [ X] I know that pull requests will not be merged if they fail the automated tests.
- [ X] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ X] All new JavaScript files are placed inside an existing directory.
- [ X] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames. …
=> chore: fix grammar error in README

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other.yml
- It is good to have a field for extra/additional information if the user wants to specify or tell something else that doesn't fit any of the provided fields in the issue form.
- Blank issues were disabled in favor of the miscellaneous/another template, which asks the user for at least a bit of information, rather than letting the user create a blank issue. This can be better for the maintainers when checking out the issues, IMO.
**Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not~
=> docs: improve the issue forms

Dynamic-Programming/Sliding-Window/HouseRobber.js, Dynamic-Programming/Sliding-Window/test/HouseRobber.test.js
=> feat: add houseRobber implementation

Dynamic-Programming/Sliding-Window/MaxConsecutiveOnes.js, Dynamic-Programming/Sliding-Window/test/MaxConsecutiveOnes.test.js
=> feat: add maxConsecutiveOnes implementation

Trees/DepthFirstSearch.js, Trees/test/DepthFirstSearch.test.js
…for DepthFirstSearch algorithm.
=> fixes: #1280 and test:  added tests for DFS algorithm 

DIRECTORY.md, Sorts/DutchNationalFlagSort.js, Sorts/test/DutchNationalFlagSort.test.js
=> feat: add dutchNationalFlagSort implementation

.github/pull_request_template.md
Corrected grammatical mistakes
=> fixed: to correct grammatical mistakes

Maths/ParityOutlier.js, Maths/test/ParityOutlier.test.js
=> New Algorithm: Parity Outlier

Data-Structures/Heap/MinPriorityQueue.js, Dynamic-Programming/SudokuSolver.js, Dynamic-Programming/UniquePaths.js, Project-Euler/Problem011.js, Recursive/BinarySearch.js, Recursive/FibonacciNumberRecursive.js, Sorts/TopologicalSort.js
I ran the command `yarn style`, but it failed. However, I managed to fix it.
=> chore: 🤖 remove extra lines

Maths/SumOfDigits.js
Update: I have Added Unary Operator (+) in SumOfDigits algorithm, It's Optimized Solution in current tech stack.
If there is any thing need to update in this PR , I'll update it.
Thanks.
=> Update: Added Unary Operator in SumOfDigits algorithm

Maths/NumberOfDigits.js, Maths/test/NumberOfDigits.test.js
I added a method which calculate number of digits using a mathematical way.
=> added numberOfDigitsUsingLog method

README.md
=> added contributor graph to the readme

Maths/ArmstrongNumber.js
=> fix: #758 optimised armstrongNumber code

Maths/QuadraticRoots.js, Maths/test/QuadraticRoots.test.js
=> Added QuadraticRoots to Math/QuadraticRoots.js

String/ReverseString.js, String/test/ReverseString.test.js
=> fix : added reverse string inplace

Maths/EuclideanDistance.js, Maths/test/EuclideanDistance.test.js
=> Added Euclidean Distance

DIRECTORY.md, Data-Structures/Heap/test/BinaryHeap.test.js, Data-Structures/Stack/EvaluateExpression.js, Data-Structures/Stack/test/EvaluateExpression.test.js, Maths/test/Determinant.test.js
Somehow, our CI did not fix this. It should perhaps be noted that our CI does `npm run style`, which applies formatting rather than "just" checking it (`--write` vs `--check`).
=> chore: format code

Data-Structures/Heap/test/BinaryHeap.test.js
there was a console.log, which is not necessary for test cases.
=> updated BinaryHeap.test.js

Search/InterpolationSearch.js
=> Remove code not needed

Recursive/test/BinaryEquivalent.test.js
=> test: add tests for Binary Equivalent Algorithm

CONTRIBUTING.md
=> docs: Update script usage in CONTRIBUTING.md

.github/workflows/UpdateDirectory.yml, DIRECTORY.md
Same as TheAlgorithms/Rust#647 - it contains the description of the problem, which this PR solves.
**Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not~
=> Properly evaluate `GITHUB_ACTOR`

.github/workflows/Ci.yml, .github/workflows/UpdateDirectory.yml
=> Update `actions/setup-node` to `v4`

.github/workflows/Ci.yml, .github/workflows/UpdateDirectory.yml
=> Update `actions/checkout` to `v4`

.github/ISSUE_TEMPLATE/bug_report.yml, .github/stale.yml
=> Remove trailing spaces

.github/workflows/UploadCoverageReport.yml, .gitignore, package-lock.json, package.json, vitest.config.ts
This PR integrated this repository with [codecov](https://app.codecov.io/gh/TheAlgorithms/JavaScript). Thanks to these changes one can also easily generate coverage report locally.
Usually I would expect a comment from codecov-bot, but it somehow does not appear. I guess it is due to #1085. The integration [_seems_ to work](https://app.codecov.io/gh/TheAlgorithms/JavaScript/pull/1599).
=> Add `UploadCoverageReport.yml`

Maths/ReverseNumber.js, Maths/test/ReverseNumber.test.js
Errors should be thrown not returned. This PR also adds tests. I do not want to specify how the `ReverseNumber` should react to negative inputs, so I did not tests covering such situation.
=> fix: throw error and add tests for `ReverseNumber`

Conversions/DateToDay.js, Conversions/test/DateToDay.test.js
Similar to #1624 - errors should be thrown not returned. Additionally, this PR reorganizes the tests.
=> fix: `throw` form `DateToDay`

Trees/DepthFirstSearch.js
=> removed code already present in test cases related to DFT in Trees folder.

.github/workflows/Ci.yml, .github/workflows/UpdateDirectory.yml, .github/workflows/UploadCoverageReport.yml, DIRECTORY.md
=> GitHub Actions: Test on the current version of Node.js

Data-Structures/Queue/QueueUsing2Stacks.js
This PR fixes the failing CI. I decided to remove these functions because of:
https://github.com/TheAlgorithms/JavaScript/blob/1554ba5f9c1bade3e52733a2bf67017b073fbe75/CONTRIBUTING.md?plain=1#L162
=> style: remove `listIn` and `listOut`
